eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://payment-servie/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://order-servie/order/bookOrder
